vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
#mappings tells to the buddle vich where to save files
    mappings:
       jtedisquoi_images:
       #path
           uri_prefix: /images/lieux
           upload_destination: '%kernel.project_dir%/public/images/lieux'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
